# Generated by Django 4.2.1 on 2023-05-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=13, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
