# Generated by Django 4.2.1 on 2023-05-16 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_product_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("IN DOOR", "In Door"), ("OUT DOOR", "Out Door")],
                default="IN DOOR",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OUT DOOR", "Pending"),
                            ("DELIVERED", "Delivered"),
                            ("OUT OF STOCK", "Out Of Stock"),
                        ],
                        default="OUT DOOR",
                        max_length=30,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_customer",
                        to="accounts.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_product",
                        to="accounts.product",
                    ),
                ),
            ],
        ),
    ]
