# Generated by Django 4.2.1 on 2023-05-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("DELIVERED", "Delivered"),
                    ("OUT OF STOCK", "Out Of Stock"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(to="accounts.tags"),
        ),
    ]
