# Generated by Django 4.2.1 on 2023-05-17 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_order_status_alter_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_product",
                to="accounts.customer",
            ),
        ),
    ]
