# Generated by Django 4.2.1 on 2023-05-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_customer_user_alter_customer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
